import type { Metadata } from "next";
import "./globals.css";
import { AppBar, Toolbar, Box } from "@mui/material";
import BurgerazemLogo from "@/components/BurgerazemLogo";
import LunchDiningOutlinedIcon from "@mui/icons-material/LunchDiningOutlined";
import ThemeRegistry from "@/components/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const APP_BAR_HEIGHT = "56px";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hr">
      <body>
        <ThemeRegistry>
          <AppBar position="fixed" sx={{ bgcolor: "#1a1a1a" }}>
            <Toolbar sx={{ minHeight: `${APP_BAR_HEIGHT} !important`, py: 1 }}>
              <Box sx={{ display: "flex", alignItems: "center" }}>
                <LunchDiningOutlinedIcon
                  sx={{ fontSize: 30, color: "primary.main", mr: 1 }}
                />
                <BurgerazemLogo fill="#ff8c00" width={150} height="auto" />
              </Box>
            </Toolbar>
          </AppBar>
          <Box
            component="main"
            sx={{
              marginTop: APP_BAR_HEIGHT,
              minHeight: "100vh",
            }}
          >
            {children}
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
